title: Towards Accurate Recommendations of Merge Conflicts Resolution Strategies 
description: Companion site for the paper "Towards Accurate Recommendations of Merge Conflicts Resolution Strategies".
theme: jekyll-theme-cayman
